TryJsonEverything/Controllers/RedirectController.cs
using Microsoft.AspNetCore.Mvc;

namespace TryJsonEverything.Controllers
{
	public class RedirectController : Controller
	{
		public IActionResult Github()
		{
			return Redirect("https://github.com/gregsdennis/json-everything");
		}

		public IActionResult Slack()
		{
			return Redirect("https://join.slack.com/t/manateeopensource/shared_invite/enQtMzU4MjgzMjgyNzU3LWZjYzAzYzY3NjY1MjY3ODI0ZGJiZjc3Nzk1MDM5NTNlMjMyOTE0MzMxYWVjMjdiOGU1NDY5OGVhMGQ5YzY4Zjg");
		}

		public IActionResult Documentation()
		{
			return Redirect("https://gregsdennis.github.io/json-everything");
		}
	}
}

TryJsonEverything/Views/Shared/_ExternalLink.cshtml
<span>
	<img class="img-text-icon" src="~/img/external-link.png"/>
</span>

TryJsonEverything/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <title>@ViewData["Title"] - json-everything</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
<header id="header" class="brand-colors">
	<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
		<div class="container">
			<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><span class="text-monospace text-white" target="_blank">json-everything</span></a>
			<div>
				<a asp-controller="Redirect" asp-action="Slack" class="mr-3 no-underline" data-toggle="tooltip" data-placement="bottom" title="Discuss in Slack" target="_blank">
					<img src="~/img/slack.png" alt="Discuss in Slack"/>
				</a>
				<a asp-controller="Redirect" asp-action="Github" class="mr-3 no-underline" data-toggle="tooltip" data-placement="bottom" title="View on GitHub" target="_blank">
					<img src="~/img/github.png" alt="View on GitHub"/>
				</a>
				<a asp-controller="Redirect" asp-action="Documentation" class="no-underline" data-toggle="tooltip" data-placement="bottom" title="Library Docs" target="_blank">
					<img src="~/img/scroll-icon.png" alt="Library Docs"/>
				</a>
			</div>
		</div>
	</nav>
</header>
<div class="container">
	<main role="main" class="pb-3">
		@RenderBody()
	</main>
</div>
<div class="options-bar position-fixed">
	@await RenderSectionAsync("OptionsBar", required: false)
</div>

<footer class="border-top footer brand-colors text-muted-light">
	<div class="container small">
		<div class="row">
			<div class="col text-muted-light">
				&copy; 2021 | <span class="text-monospace">json-everything</span> | <a class="text-muted-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
			</div>
			<div class="col text-right">
				<a class="text-muted-light" asp-area="" asp-controller="Home" asp-action="Schema">JSON Schema</a> |
				<a class="text-muted-light" asp-area="" asp-controller="Home" asp-action="Path">JSON Path</a> |
				<a class="text-muted-light" asp-area="" asp-controller="Home" asp-action="Patch">JSON Patch</a> |
				<a class="text-muted-light" asp-area="" asp-controller="Home" asp-action="Logic">JSON Logic</a> |
				<a class="text-muted-light" asp-area="" asp-controller="Home" asp-action="Pointer">JSON Pointer</a>
			</div>
		</div>
	</div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript">
	const baseUri = '@($"https://{Context.Request.Host.Value}{Url.Content("~/")}")';
</script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>